spring:
  application:
    name: interview
  profiles:
    active: local
  docker:
    compose:
      enabled: true

server:
  port: 8080

app:
  auth:
    max-send-count: 5
    min-send-count: 0
    verification-expiration-minutes: 10
    count-reset-hours: 24
